# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8301:8301"
  web:
    build: ./web
    env_file: .env
    ports:
      - "8300:8300"
    depends_on:
      - api
