#!/bin/bash

if [ -z "WEB_PORT" ]; then
    echo "WEB_PORT is not set: will default to 8400"
fi

# Use port 8300 if not set
PORT=${WEB_PORT:-8400}

streamlit run  app.py --server.port=${PORT} --server.address=0.0.0.0